# Generated by Django 2.1.3 on 2018-11-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('did', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('geoinfo', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('offense_description', models.CharField(blank=True, max_length=100, null=True)),
                ('shooting', models.CharField(blank=True, max_length=40, null=True)),
                ('offense_code_group', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffenseCode',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'offense_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('pid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ps_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'police_station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentLocation',
            fields=[
                ('incident_num', models.ForeignKey(db_column='incident_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='IL_incident_num', serialize=False, to='BC.Incident')),
                ('street', models.CharField(blank=True, max_length=40, null=True)),
                ('reporting_area', models.CharField(blank=True, max_length=5, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longtitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'incident_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentTime',
            fields=[
                ('incident_num', models.ForeignKey(db_column='incident_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='IT_incident_num', serialize=False, to='BC.Incident')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('dayofweek', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'incident_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PsLocation',
            fields=[
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BC.PoliceStation')),
                ('street', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=5, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longtitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'ps_location',
                'managed': False,
            },
        ),
    ]
